# pod-with-nginx-config.yaml
# ConfigMapをファイルとしてマウントするPod

apiVersion: v1
kind: Pod
metadata:
  name: nginx-config-demo
spec:
  containers:
    - name: nginx
      image: nginx:1.25
      ports:
        - containerPort: 80

      # ConfigMapをファイルとしてマウント
      volumeMounts:
        - name: nginx-conf-volume          # ボリューム名
          mountPath: /etc/nginx/conf.d     # マウント先のパス
          readOnly: true

  # ボリュームの定義
  volumes:
    - name: nginx-conf-volume              # volumeMountsのnameと一致させる
      configMap:
        name: nginx-config                 # ConfigMap名
