# prod-deployment.yaml
# production 用のDeployment

apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
  namespace: production         # ← Namespace を指定
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: nginx
          image: nginx:1.25     # 本番は安定バージョン
          ports:
            - containerPort: 80
